### ISSUE TITLE
sec11/index.html -> **Top Songs** `mouse over` not showing the music symbol.

### ISSUE THREAD

**Issue by leninworld** [agalyablue/udemy_bootstrap_10projects#10]
sec11/index.html -> **Top Songs** `mouse over` not showing the music symbol.

**Comment by agalyablue** [comment]
now change and gitpush sec11 redone and now showing the music symbol

**Comment by agalyablue** [comment]
fixed the issue

**Comment by agalyablue** [comment]
add comment in the gitpush i completed
