### ISSUE TITLE
sec12 -> DOUGHNUT CHART 

### ISSUE THREAD

**Issue by leninworld** [agalyablue/udemy_bootstrap_10projects#13]
In the card `DOUGHNUT CHART` -> Broken into two lines -> it should in a single line

**Comment by agalyablue** [comment]
mama no its correct go to udemy videos and check sec12 its correct doughnut chart into 2 lines not single line ok

**Comment by leninworld** [comment]
Ok.

**Comment by leninworld** [comment]
You can close this issue
